<?php 

function dchcustom_cron() {
	if ( date("G") == 5 ){
	// if during the 5 AM time frame, then perform data load
		// dchcustom_import_products_stock();	
	} // end if	
} // end function 

/**
 * Import products that have files loaded on the server.
 */
function dchcustom_import_products_stock() {
	$transaction = db_transaction();

	try{
		// see if sku exists

		// if sku exists, then update it 		

		$query = "update {uc_product_stock} set stock=(stock+1) where sku=:sku";
		$result = db_query($query, array(":sku" => $fsku));

		
	} catch (Exception $e) {
		watchdog_exception('dchcustom', $e, NULL, array(), WATCHDOG_ERROR, NULL);
	} // end catch
} // function

function dchcustom_block_info() {
  $blocks['dchcustom_simplisafe'] = array(
    'info' => t('Alarm Status'),
    'cache' => DRUPAL_NO_CACHE,
  );
	
  return $blocks;
} // end function dchcustom_block_info()

function dchcustom_block_view($delta = '') {
  switch($delta) {
    case 'dchcustom_simplisafe':
      $block['subject'] = t('Alarm Status');
      $block['content'] = t(variable_get('dchcustom_alarm_status', 'Unknown');
      break;
  } // end switch

  return $block;
} // end function 

