<?php 

function dchcustom_inetspeed_enable() {
  variable_set('dchcustom_inetspeed_delimter', ';');
  variable_set('dchcustom_inetspeed_field_keys', '');
  variable_set('dchcustom_inetspeed_path', '');
} // end function 

function dchcustom_inetspeed_uninstall() {
  variable_del('dchcustom_inetspeed_delimiter');
  variable_del('dchcustom_inetspeed_field_keys');
  variable_del('dchcustom_inetspeed_path');
} // end function

